export const permissionSlugs = [
  "platform.foundation.access",
  "auth.session.read",
  "auth.session.write",
  "users.read",
  "roles.read",
  "roles.manage",
  "audit.read",
  "audit.write",
  "audit.export",
  "files.read",
  "files.write",
  "storage.configure",
  "projects.read",
  "projects.create",
  "projects.update",
  "projects.manage_status",
  "project_members.read",
  "project_members.manage",
  "events.read",
  "events.create",
  "events.update",
  "event_members.read",
  "event_members.manage",
  "workflow_tasks.read",
  "workflow_tasks.update",
  "guests.read",
  "guests.create",
  "guests.update",
  "guests.deactivate",
  "guests.manage_bride_side",
  "guests.manage_groom_side",
  "guest_title_types.manage",
  "guest_tags.manage",
  "guest_event_assignments.manage",
  "guest_duplicates.read",
  "guest_duplicates.manage",
  "guest_imports.read",
  "guest_imports.create",
  "guest_imports.submit",
  "guest_imports.review",
  "guest_imports.apply",
  "guest_public_pages.preview",
  "guest_public_tokens.manage",
  "rsvps.read",
  "rsvps.manage",
  "invitation_templates.read",
  "invitation_templates.create",
  "invitation_templates.update",
  "invitation_templates.approve",
  "invitations.read",
  "invitations.generate",
  "invitation_files.read",
  "message_templates.read",
  "message_templates.manage",
  "messages.read",
  "messages.prepare",
  "messages.send",
  "seating.read",
  "seating.tables.manage",
  "seating.assign",
  "seating.export",
  "check_in.read",
  "check_in.settings.manage",
  "check_in.tokens.manage",
  "check_in.search",
  "check_in.perform",
  "check_in.unexpected_guests.create",
  "check_in.unexpected_guests.review",
  "check_in.devices.manage",
  "check_in.offline_sync",
  "check_in.dashboard",
  "guest_messages.read",
  "guest_messages.moderate",
  "guest_messages.couple_review",
  "guest_book_exports.read",
  "guest_book_exports.create",
  "post_event_feedback.submit",
  "post_event_feedback.read",
  "post_event_feedback.review",
  "dashboards.global.read",
  "dashboards.project.read",
  "dashboards.event.read",
  "dashboards.couple.read",
  "dashboards.partner.read",
  "reports.catalog.read",
  "reports.export",
  "reports.internal.read",
  "service_packages.read",
  "service_packages.manage",
  "pricing.read",
  "pricing.calculate",
  "pricing.manage",
  "contracts.read",
  "contracts.generate",
  "contracts.approve",
  "contracts.manage_addendums",
  "payments.summary.read",
  "payments.read",
  "payments.record",
  "payments.confirm",
  "payment_exceptions.manage",
  "commercial_gestures.manage",
  "revenue.read",
] as const;

export type PermissionSlug = (typeof permissionSlugs)[number];

export type RoleScope = "global" | "project" | "event" | "custom";

export type RoleSlug =
  | "diginoces_admin"
  | "operations_manager"
  | "role_manager"
  | "audit_viewer"
  | "file_manager"
  | "couple"
  | "bride"
  | "groom"
  | "event_staff"
  | "check_in_supervisor"
  | "partner_admin";

export type RoleDefinition = {
  description: string;
  grants: PermissionSlug[];
  requirementIds: string[];
  requiresMfa: boolean;
  scope: RoleScope;
  slug: RoleSlug;
};

export const roleDefinitions: Record<RoleSlug, RoleDefinition> = {
  audit_viewer: {
    description: "Can review and export foundation audit records.",
    grants: ["audit.read", "audit.export", "reports.catalog.read"],
    requirementIds: ["REP-006", "ROLE-007"],
    requiresMfa: true,
    scope: "global",
    slug: "audit_viewer",
  },
  couple: {
    description: "Future project-level wedding couple role.",
    grants: [
      "platform.foundation.access",
      "projects.read",
      "events.read",
      "workflow_tasks.read",
      "guests.read",
      "guest_duplicates.read",
      "rsvps.read",
      "seating.read",
      "contracts.read",
      "contracts.approve",
      "payments.summary.read",
      "dashboards.project.read",
      "dashboards.couple.read",
      "reports.catalog.read",
      "reports.export",
      "guest_messages.read",
      "guest_messages.couple_review",
      "guest_book_exports.read",
      "post_event_feedback.submit",
      "post_event_feedback.read",
    ],
    requirementIds: [
      "PV-002",
      "ROLE-002",
      "PROJ-001",
      "PROJ-002",
      "GM-001",
      "SEAT-001",
      "SEAT-005",
      "SEAT-006",
      "SEAT-007",
      "RSVP-010",
      "PAY-001",
      "PAY-002",
      "PAY-003",
      "PAY-013",
      "REP-001",
      "REP-003",
      "REP-005",
      "WISH-006",
    ],
    requiresMfa: false,
    scope: "project",
    slug: "couple",
  },
  bride: {
    description: "Project-level bride role with own-side guest management.",
    grants: [
      "platform.foundation.access",
      "projects.read",
      "events.read",
      "workflow_tasks.read",
      "guests.read",
      "guests.manage_bride_side",
      "guest_title_types.manage",
      "guest_tags.manage",
      "guest_event_assignments.manage",
      "guest_duplicates.read",
      "guest_imports.read",
      "guest_imports.create",
      "guest_imports.submit",
      "rsvps.read",
      "seating.read",
      "seating.assign",
      "contracts.read",
      "contracts.approve",
      "payments.summary.read",
      "dashboards.project.read",
      "dashboards.couple.read",
      "reports.catalog.read",
      "reports.export",
      "guest_messages.read",
      "guest_messages.couple_review",
      "guest_book_exports.read",
      "post_event_feedback.submit",
      "post_event_feedback.read",
    ],
    requirementIds: [
      "ROLE-005",
      "GM-002",
      "GM-003",
      "GM-011",
      "SEAT-001",
      "SEAT-005",
      "SEAT-006",
      "SEAT-007",
      "SEAT-008",
      "SEAT-009",
      "RSVP-010",
      "PAY-001",
      "PAY-002",
      "PAY-003",
      "PAY-013",
      "REP-001",
      "REP-003",
      "REP-005",
      "TECH-004",
      "WISH-006",
    ],
    requiresMfa: false,
    scope: "project",
    slug: "bride",
  },
  diginoces_admin: {
    description: "Internal administrator with foundation-level access.",
    grants: [...permissionSlugs],
    requirementIds: ["PV-001", "ROLE-001", "ROLE-007"],
    requiresMfa: true,
    scope: "global",
    slug: "diginoces_admin",
  },
  check_in_supervisor: {
    description:
      "Event-level supervisor for unexpected guest approvals, devices, and arrivals dashboard.",
    grants: [
      "platform.foundation.access",
      "events.read",
      "seating.read",
      "check_in.read",
      "check_in.search",
      "check_in.perform",
      "check_in.unexpected_guests.create",
      "check_in.unexpected_guests.review",
      "check_in.devices.manage",
      "check_in.offline_sync",
      "check_in.dashboard",
      "dashboards.event.read",
      "reports.catalog.read",
      "reports.export",
    ],
    requirementIds: [
      "ROLE-006",
      "CHK-001",
      "CHK-002",
      "CHK-004",
      "CHK-008",
      "CHK-009",
      "CHK-011",
      "CHK-013",
      "CHK-014",
      "REP-001",
      "REP-005",
      "TECH-007",
    ],
    requiresMfa: true,
    scope: "event",
    slug: "check_in_supervisor",
  },
  event_staff: {
    description:
      "Event-level staff role with limited wedding-day operational access.",
    grants: [
      "platform.foundation.access",
      "events.read",
      "seating.read",
      "check_in.read",
      "check_in.search",
      "check_in.perform",
      "check_in.unexpected_guests.create",
      "check_in.offline_sync",
      "dashboards.event.read",
      "reports.catalog.read",
      "reports.export",
    ],
    requirementIds: [
      "ROLE-003",
      "ROLE-006",
      "PROJ-002",
      "SEAT-001",
      "SEAT-005",
      "SEAT-006",
      "SEAT-007",
      "RSVP-010",
      "CHK-001",
      "CHK-002",
      "CHK-004",
      "CHK-011",
      "CHK-012",
      "REP-001",
      "REP-005",
    ],
    requiresMfa: false,
    scope: "event",
    slug: "event_staff",
  },
  groom: {
    description: "Project-level groom role with own-side guest management.",
    grants: [
      "platform.foundation.access",
      "projects.read",
      "events.read",
      "workflow_tasks.read",
      "guests.read",
      "guests.manage_groom_side",
      "guest_title_types.manage",
      "guest_tags.manage",
      "guest_event_assignments.manage",
      "guest_duplicates.read",
      "guest_imports.read",
      "guest_imports.create",
      "guest_imports.submit",
      "rsvps.read",
      "seating.read",
      "seating.assign",
      "contracts.read",
      "contracts.approve",
      "payments.summary.read",
      "dashboards.project.read",
      "dashboards.couple.read",
      "reports.catalog.read",
      "reports.export",
      "guest_messages.read",
      "guest_messages.couple_review",
      "guest_book_exports.read",
      "post_event_feedback.submit",
      "post_event_feedback.read",
    ],
    requirementIds: [
      "ROLE-005",
      "GM-002",
      "GM-003",
      "GM-011",
      "SEAT-001",
      "SEAT-005",
      "SEAT-006",
      "SEAT-007",
      "SEAT-008",
      "SEAT-009",
      "RSVP-010",
      "PAY-001",
      "PAY-002",
      "PAY-003",
      "PAY-013",
      "REP-001",
      "REP-003",
      "REP-005",
      "TECH-004",
      "WISH-006",
    ],
    requiresMfa: false,
    scope: "project",
    slug: "groom",
  },
  file_manager: {
    description:
      "Can manage app-owned operational files through approved services.",
    grants: ["files.read", "files.write", "storage.configure"],
    requirementIds: ["FILE-001"],
    requiresMfa: false,
    scope: "global",
    slug: "file_manager",
  },
  operations_manager: {
    description:
      "Can operate foundation services without sensitive admin controls.",
    grants: [
      "platform.foundation.access",
      "auth.session.read",
      "users.read",
      "roles.read",
      "files.read",
      "projects.read",
      "projects.create",
      "projects.update",
      "events.read",
      "events.create",
      "events.update",
      "workflow_tasks.read",
      "workflow_tasks.update",
      "guests.read",
      "guests.create",
      "guests.update",
      "guests.deactivate",
      "guest_title_types.manage",
      "guest_tags.manage",
      "guest_event_assignments.manage",
      "guest_duplicates.read",
      "guest_duplicates.manage",
      "guest_imports.read",
      "guest_imports.create",
      "guest_imports.submit",
      "guest_imports.review",
      "guest_imports.apply",
      "guest_public_pages.preview",
      "guest_public_tokens.manage",
      "rsvps.read",
      "rsvps.manage",
      "invitation_templates.read",
      "invitation_templates.create",
      "invitation_templates.update",
      "invitation_templates.approve",
      "invitations.read",
      "invitations.generate",
      "invitation_files.read",
      "message_templates.read",
      "message_templates.manage",
      "messages.read",
      "messages.prepare",
      "messages.send",
      "seating.read",
      "seating.tables.manage",
      "seating.assign",
      "seating.export",
      "check_in.read",
      "check_in.settings.manage",
      "check_in.tokens.manage",
      "check_in.search",
      "check_in.perform",
      "check_in.unexpected_guests.create",
      "check_in.unexpected_guests.review",
      "check_in.devices.manage",
      "check_in.offline_sync",
      "check_in.dashboard",
      "dashboards.global.read",
      "dashboards.project.read",
      "dashboards.event.read",
      "reports.catalog.read",
      "reports.export",
      "guest_messages.read",
      "guest_messages.moderate",
      "guest_messages.couple_review",
      "guest_book_exports.read",
      "guest_book_exports.create",
      "post_event_feedback.submit",
      "post_event_feedback.read",
      "post_event_feedback.review",
      "reports.internal.read",
      "service_packages.read",
      "service_packages.manage",
      "pricing.read",
      "pricing.calculate",
      "pricing.manage",
      "contracts.read",
      "contracts.generate",
      "contracts.manage_addendums",
      "payments.summary.read",
      "payments.read",
      "payments.record",
      "payments.confirm",
      "payment_exceptions.manage",
      "commercial_gestures.manage",
      "revenue.read",
    ],
    requirementIds: [
      "PV-001",
      "PV-002",
      "ROLE-001",
      "PROJ-001",
      "PROJ-002",
      "GM-001",
      "GM-003",
      "INV-001",
      "INV-002",
      "INV-003",
      "INV-004",
      "INV-005",
      "INV-006",
      "INV-007",
      "INV-008",
      "INV-011",
      "INV-012",
      "INV-014",
      "INV-015",
      "FILE-004",
      "FILE-005",
      "FILE-006",
      "REP-006",
      "MSG-001",
      "MSG-002",
      "MSG-003",
      "MSG-004",
      "MSG-005",
      "MSG-006",
      "MSG-007",
      "MSG-008",
      "MSG-009",
      "MSG-010",
      "SEAT-001",
      "SEAT-002",
      "SEAT-003",
      "SEAT-004",
      "SEAT-005",
      "SEAT-006",
      "SEAT-007",
      "SEAT-008",
      "SEAT-009",
      "SEAT-011",
      "CHK-001",
      "CHK-002",
      "CHK-003",
      "CHK-004",
      "CHK-005",
      "CHK-006",
      "CHK-008",
      "CHK-009",
      "CHK-010",
      "CHK-011",
      "CHK-012",
      "CHK-013",
      "CHK-014",
      "RSVP-010",
      "FILE-008",
      "TECH-004",
      "TECH-007",
      "TECH-010",
      "PAY-001",
      "PAY-005",
      "PAY-006",
      "PAY-007",
      "PAY-008",
      "PAY-009",
      "PAY-010",
      "PAY-011",
      "PAY-013",
      "PAY-014",
      "REP-001",
      "REP-002",
      "REP-005",
      "REP-006",
      "REP-007",
      "WISH-001",
      "WISH-004",
      "WISH-006",
      "WISH-007",
      "WISH-008",
    ],
    requiresMfa: true,
    scope: "global",
    slug: "operations_manager",
  },
  partner_admin: {
    description: "Future restricted partner administrator role.",
    grants: ["platform.foundation.access", "dashboards.partner.read"],
    requirementIds: ["ROLE-002", "ROLE-004", "ROLE-007", "REP-004"],
    requiresMfa: true,
    scope: "custom",
    slug: "partner_admin",
  },
  role_manager: {
    description: "Can manage roles and permissions.",
    grants: ["roles.read", "roles.manage", "audit.write"],
    requirementIds: ["ROLE-001", "ROLE-007"],
    requiresMfa: true,
    scope: "global",
    slug: "role_manager",
  },
};

export type RoleAssignment = {
  role: RoleSlug;
  scope: RoleScope;
  scopeId?: string;
};

function getRoleDefinition(role: string) {
  return (roleDefinitions as Partial<Record<string, RoleDefinition>>)[role];
}

export function isValidRoleAssignment(assignment: RoleAssignment) {
  const roleDefinition = getRoleDefinition(assignment.role);

  if (!roleDefinition || assignment.scope !== roleDefinition.scope) {
    return false;
  }

  if (assignment.scope === "global") {
    return !assignment.scopeId;
  }

  return (
    typeof assignment.scopeId === "string" && assignment.scopeId.length > 0
  );
}

export function getValidRoleAssignments(assignments: RoleAssignment[]) {
  return assignments.filter(isValidRoleAssignment);
}

export function getGrantedPermissions(assignments: RoleAssignment[]) {
  return new Set(
    getValidRoleAssignments(assignments).flatMap(
      (assignment) => roleDefinitions[assignment.role].grants,
    ),
  );
}

export function hasPermission(
  assignments: RoleAssignment[],
  permission: PermissionSlug,
) {
  return getGrantedPermissions(assignments).has(permission);
}

export function sensitiveRolesRequireMfa(assignments: RoleAssignment[]) {
  return getValidRoleAssignments(assignments).some(
    (assignment) => roleDefinitions[assignment.role].requiresMfa,
  );
}
